# Compiler and flags
CC = g++
CFLAGS = -Wall -std=c++11

# Target executable
TARGET = simpleFactory

# Source file
SRC = SimpleFactory.cpp

# The default target
all: 
	$(CC) $(CFLAGS) -o  $(TARGET) $(SRC)